### ISSUE TITLE
Add toggle to exclude contacts

### ISSUE THREAD

**Issue by ItsPaPPy** [a2/TrollDropKit#3]
I was testing this out while waiting to board a flight with my spouse, and was flooding their phone, because they were a contact, and their air drop was set to contacts only.

My suggestion is, if there is a way to set a toggle to exclude contacts, that would be great.

**Comment by a2** [comment]
Hey @ItsPaPPy, I've discontinued working on TrollDropKit for the time being because iOS 12 and up require a special entitlement to use AirDrop now. Sorry for the inconvenience.
